import { trpc } from '../../../lib/trpc'
import { createAccount, getAccountById } from '../../../mongodb/account/AcoountRepository'
import { zInitLocalTrpcInput } from './input'

export const initLocalTrpcRoute = trpc.procedure.input(zInitLocalTrpcInput).mutation(async ({ input }) => {
  let account = await getAccountById(input.playerId)
  if (!account) {
    const randomName = getRandomName()
    account = await createAccount(input.playerId, randomName, randomName)
  }
  return { success: true }
})

const names = [
  'Alice',
  'Bob',
  'Charlie',
  'David',
  'Eva',
  'Frank',
  'Grace',
  'Hannah',
  'Ivy',
  'Jack',
  'Kathy',
  'Liam',
  'Megan',
  'Nathan',
  'Olivia',
  'Paul',
  'Quinn',
  'Rachel',
  'Sam',
  'Tina',
  'Ursula',
  'Victor',
  'Wendy',
  'Xander',
  'Yara',
  'Zane',
  'Анна',
  'Борис',
  'Вера',
  'Григорий',
  'Даша',
  'Евгений',
  'Жанна',
  'Иван',
  'Кира',
  'Леонид',
  'Марина',
  'Никита',
  'Ольга',
  'Петр',
  'Роман',
  'Светлана',
  'Тимур',
  'Ульяна',
  'Федор',
  'Христина',
  'Цветана',
  'Шамиль',
  'Элина',
  'Юрий',
  'Ярослав',
  'Алексей',
  'Владимир',
  'Ирина',
  'Ксения',
  'Людмила',
  'Максим',
  'Нина',
  'Оксана',
  'Павел',
  'Рената',
  'Сергей',
  'Татьяна',
  'Устин',
  'Филипп',
  'Хавьер',
  'Цезарь',
  'Шерил',
  'Эдвард',
  'Юлия',
  'Яна',
  'Алиса',
  'Бенжамин',
  'Виктория',
  'Георгий',
  'Дарина',
  'Егор',
  'Женя',
  'Игорь',
  'Кристина',
  'Лев',
  'Маргарита',
  'Надежда',
  'Олег',
  'Петр',
  'Радмила',
  'Станислав',
  'Тимофей',
  'Устина',
  'Фаина',
  'Христофор',
  'Цветан',
  'Шон',
  'Эмма',
  'Юлиан',
  'Ярослава',
  'Анатолий',
  'Богдан',
  'Валерия',
  'Глеб',
  'Дмитрий',
  'Елена',
  'Захар',
  'Ирина',
]

function getRandomName(): string {
  const randomIndex = Math.floor(Math.random() * names.length)
  return names[randomIndex]
}
